spring:
  application:
    name: Reactive Demo
  r2dbc:
    url: r2dbc:postgresql://localhost:5433/spring_reactive
    username: bheema
    password: admin123
  flyway:
    baseline-on-migrate: true
    enabled: true
    baseline-description: "Init"
    baseline-version: 0
    url: jdbc:postgresql://localhost:5433/spring_reactive
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}